version: '3'
services:
  api:
    container_name: "userapi"
    image: journey_sharing_app:v1
    # build: .
    entrypoint: python app.py
    ports:
        - '5000:5000'
    volumes:
      - .:/app
    depends_on:
      - db
    restart: on-failure:15
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
  db:
    container_name: "mysql_container"
    image: mysql_container:1.0.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqlvol:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis
    ports:
      - "6379:6379"
 # reoutehandler:
  #  image: nginix_route_handler:1.0.0
  #  ports:
   #   - 80:80

volumes:
  mysqlvol: null



