"""empty message

Revision ID: 6f01c9c4577d
Revises: 7357f3854c63
Create Date: 2022-03-24 18:39:15.848488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f01c9c4577d'
down_revision = '7357f3854c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating_count', sa.Integer(), nullable=True))
    op.drop_column('users', 'travel_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('travel_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'rating_count')
    # ### end Alembic commands ###
