"""empty message

Revision ID: 7357f3854c63
Revises: 
Create Date: 2022-03-24 17:20:13.801502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7357f3854c63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_rating', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('travel_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'travel_count')
    op.drop_column('users', 'current_rating')
    # ### end Alembic commands ###
